/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyRouteImport } from './routes/study'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as DecksRouteImport } from './routes/decks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DecksDeckIdRouteImport } from './routes/decks.$deckId'
import { Route as StudyDeckIdModeRouteImport } from './routes/study.$deckId.$mode'

const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksRoute = DecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdRoute = DecksDeckIdRouteImport.update({
  id: '/$deckId',
  path: '/$deckId',
  getParentRoute: () => DecksRoute,
} as any)
const StudyDeckIdModeRoute = StudyDeckIdModeRouteImport.update({
  id: '/$deckId/$mode',
  path: '/$deckId/$mode',
  getParentRoute: () => StudyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decks': typeof DecksRouteWithChildren
  '/lookup': typeof LookupRoute
  '/study': typeof StudyRouteWithChildren
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/study/$deckId/$mode': typeof StudyDeckIdModeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decks': typeof DecksRouteWithChildren
  '/lookup': typeof LookupRoute
  '/study': typeof StudyRouteWithChildren
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/study/$deckId/$mode': typeof StudyDeckIdModeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decks': typeof DecksRouteWithChildren
  '/lookup': typeof LookupRoute
  '/study': typeof StudyRouteWithChildren
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/study/$deckId/$mode': typeof StudyDeckIdModeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/decks'
    | '/lookup'
    | '/study'
    | '/decks/$deckId'
    | '/study/$deckId/$mode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/decks'
    | '/lookup'
    | '/study'
    | '/decks/$deckId'
    | '/study/$deckId/$mode'
  id:
    | '__root__'
    | '/'
    | '/decks'
    | '/lookup'
    | '/study'
    | '/decks/$deckId'
    | '/study/$deckId/$mode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecksRoute: typeof DecksRouteWithChildren
  LookupRoute: typeof LookupRoute
  StudyRoute: typeof StudyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks': {
      id: '/decks'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId': {
      id: '/decks/$deckId'
      path: '/$deckId'
      fullPath: '/decks/$deckId'
      preLoaderRoute: typeof DecksDeckIdRouteImport
      parentRoute: typeof DecksRoute
    }
    '/study/$deckId/$mode': {
      id: '/study/$deckId/$mode'
      path: '/$deckId/$mode'
      fullPath: '/study/$deckId/$mode'
      preLoaderRoute: typeof StudyDeckIdModeRouteImport
      parentRoute: typeof StudyRoute
    }
  }
}

interface DecksRouteChildren {
  DecksDeckIdRoute: typeof DecksDeckIdRoute
}

const DecksRouteChildren: DecksRouteChildren = {
  DecksDeckIdRoute: DecksDeckIdRoute,
}

const DecksRouteWithChildren = DecksRoute._addFileChildren(DecksRouteChildren)

interface StudyRouteChildren {
  StudyDeckIdModeRoute: typeof StudyDeckIdModeRoute
}

const StudyRouteChildren: StudyRouteChildren = {
  StudyDeckIdModeRoute: StudyDeckIdModeRoute,
}

const StudyRouteWithChildren = StudyRoute._addFileChildren(StudyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecksRoute: DecksRouteWithChildren,
  LookupRoute: LookupRoute,
  StudyRoute: StudyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
